### ISSUE TITLE
Full Roadmap

### ISSUE THREAD

**Issue by eXCom** [eXCom/laravel-roadmap#1]
[Source](https://github.com/LaravelDaily/Laravel-Roadmap-Learning-Path)

Link icons: 📖 Official Docs 🎬 Video 📄 Article 🔠 Course

### **Beginner Level**

**Routing and Controllers: Basics**

- [ ] Callback Functions and Route::view() 📖 [Basic Routing](https://laravel.com/docs/8.x/routing#basic-routing) 📖 [View Routes](https://laravel.com/docs/8.x/routing#view-routes)
- [ ] Routing to a Single Controller Method 📖 [Basic controllers with routes](https://laravel.com/docs/8.x/controllers#basic-controllers)
- [ ] Route Parameters 📖 [Route Parameters](https://laravel.com/docs/8.x/routing#route-parameters)
- [ ] Route Naming 📖 [Names Routes](https://laravel.com/docs/8.x/routing#named-routes)
- [ ] Route Groups 📖 [Route Groups](https://laravel.com/docs/8.x/routing#route-groups)

**Blade Basics**

- [ ] Displaying Variables in Blade 📖 [Blade: Displaying Data](https://laravel.com/docs/8.x/blade#displaying-data)
- [ ] Blade If-Else and Loop Structures 📖  [Blade: If-Statements](https://laravel.com/docs/8.x/blade#if-statements) 📖 [Blade Loops](https://laravel.com/docs/8.x/blade#loops)
- [ ] Layout: @include, @extends, @section, @yield 📖 [Blade: Layout Using Template Inheritance](https://laravel.com/docs/8.x/blade#layouts-using-template-inheritance)
- [ ] Blade Components 📖 [Blade Components](https://laravel.com/docs/8.x/blade#components) 🎬 [Laravel Blade Components: Two Examples - Laravel Breeze/UI](https://www.youtube.com/watch?v=HybWBINeXMw)

**Auth Basics**

- [ ] Starter Kits: Breeze (Tailwind) or Laravel UI (Bootstrap) 📖 [Laravel Breeze Official Documentation](https://laravel.com/docs/8.x/starter-kits#laravel-breeze) 📖 [Laravel UI: Official Github Page](https://github.com/laravel/ui)
- [ ] Default Auth Model and Access its Fields from Anywhere 📖 [Retrieving the Authenticated User](https://laravel.com/docs/8.x/authentication#retrieving-the-authenticated-user)
- [ ] Check Auth in Controller / Blade 📖 [Determining If The Current User Is Authenticated](https://laravel.com/docs/8.x/authentication#determining-if-the-current-user-is-authenticated) 📖 [Blade: Authentication Directives](https://laravel.com/docs/8.x/blade#authentication-directives)
- [ ] Auth Middleware 📖 [Protecting Routes](https://laravel.com/docs/8.x/authentication#protecting-routes)

**Database Basics**

- [ ] Database Migrations 📖 [Database Migrations](https://laravel.com/docs/8.x/migrations)
- [ ] Basic Eloquent Model and MVC: Controller -> Model -> View 📖 [Eloquent: Getting Started](https://laravel.com/docs/8.x/eloquent)
- [ ] Eloquent Relationships: belongsTo / hasMany / belongsToMany 📖 [Eloquent Relationships: One-to-Many](https://laravel.com/docs/8.x/eloquent-relationships#one-to-many) 📖 [Eloquent Relationships: BelongsTo](https://laravel.com/docs/8.x/eloquent-relationships#one-to-many-inverse) 📖 [Eloquent Relationships: Many-to-Many](https://laravel.com/docs/8.x/eloquent-relationships#many-to-many)
- [ ] Eager Loading and N+1 Query Problem 📖 [Relationships: Eager Loading](https://laravel.com/docs/8.x/eloquent-relationships#eager-loading)

**Full Simple CRUD**

- [ ] Route Resource and Resourceful Controllers 📖 [Laravel Resource Controllers](https://laravel.com/docs/8.x/controllers#resource-controllers) 📄 [Simple Laravel CRUD with Resource Controllers [digitalocean.com]](https://www.digitalocean.com/community/tutorials/simple-laravel-crud-with-resource-controllers)
- [ ] Forms, Validation and Form Requests 📖 [Laravel Validation](https://laravel.com/docs/8.x/validation)
- [ ] File Uploads and Storage Folder Basics 📖 [Filesystem: File Uploads](https://laravel.com/docs/8.x/filesystem#file-uploads)
- [ ] Table Pagination 📖 [Database Pagination](https://laravel.com/docs/8.x/pagination)

### **Advanced Beginner Level**

**Routing Advanced**

- [ ] Route Model Binding 1) [Route Model Binding](https://laravel.com/docs/8.x/routing#route-model-binding) 2) [Laravel Route Model Binding: All You Need To Know](https://www.youtube.com/watch?v=6dEfxGLgevM)
- [ ] Route Redirect [Redirect Routes](https://laravel.com/docs/8.x/routing#redirect-routes)

**Middleware**

- [ ] Create Custom Middleware Class [Defining Middleware](https://laravel.com/docs/8.x/middleware#defining-middleware)

**Database Advanced**

- [ ] Database Seeders and Factories 1) [Database: Seeding](https://laravel.com/docs/8.x/seeding) 2) [Defining Model Factories](https://laravel.com/docs/8.x/database-testing#defining-model-factories)
- [ ] Eloquent Query Scopes [Eloquent: Query Scopes](https://laravel.com/docs/8.x/eloquent#query-scopes)
- [ ] Polymorphic relationships [Polymorphic Relationships](https://laravel.com/docs/8.x/eloquent-relationships#polymorphic-relationships)
- [ ] Eloquent Accessors and Mutators [Accessors & Mutators](https://laravel.com/docs/8.x/eloquent-mutators#accessors-and-mutators)
- [ ] Eloquent Collections 1) [Eloquent Collections](https://laravel.com/docs/8.x/eloquent-collections) 2) [General Laravel Collections](https://laravel.com/docs/8.x/collections)
- [ ] Soft Deletes [Soft Deleting](https://laravel.com/docs/8.x/eloquent#soft-deleting)

**Auth Advanced**

- [ ] Authorization: Roles/Permissions, Gates, Policies 1) [Authorization](https://laravel.com/docs/8.x/authorization) 2) [Laravel Roles and Permissions: All CORE Things You Need To Know](https://www.youtube.com/watch?v=kZOgH3-0Bko)
- [ ] Authorization: Extra Packages - Spatie Permission, Bouncer, etc 1) [Spatie Laravel Permission: Example Project Review](https://www.youtube.com/watch?v=NgToi0uiMNQ) 2) [Two Best Laravel Packages to Manage Roles/Permissions](https://laravel-news.com/two-best-roles-permissions-packages) 3) [spatie/laravel-permission](https://github.com/spatie/laravel-permission) 4) [JosephSilber/bouncer](https://github.com/JosephSilber/bouncer)
- [ ] Authentication: Email Verification [Email Verification](https://laravel.com/docs/8.x/verification)

**File Uploads Advanced** [File Uploads in Laravel](https://laraveldaily.teachable.com/p/file-uploads-in-laravel)

- [ ] Drivers and Disks, Example of Amazon S3 1) [File Storage](https://laravel.com/docs/8.x/filesystem) 2) [Laravel: How to Upload Files to Amazon S3](https://www.youtube.com/watch?v=xZQM9q_QxMA)
- [ ] Extra Packages: Spatie Medialibrary, Intervention Image, etc 1) [spatie/laravel-medialibrary](https://github.com/spatie/laravel-medialibrary) 2) [intervention/image](https://github.com/Intervention/image)

**API Basics** [How to Create Laravel API](https://laraveldaily.teachable.com/p/how-to-create-laravel-api)

- [ ] API Routes and Controllers  1) [API Resource Routes](https://laravel.com/docs/8.x/controllers#api-resource-routes) 2) [Default Route Files](https://laravel.com/docs/8.x/routing#the-default-route-files)
- [ ] Working with API Clients: Postman or Alternatives [Postman API Client](https://www.postman.com/product/api-client/)
- [ ] API Eloquent Resources [Eloquent: API Resources](https://laravel.com/docs/8.x/eloquent-resources)
- [ ] API Auth with Sanctum [Laravel Sanctum](https://laravel.com/docs/8.x/sanctum)
- [ ] API Error Handling and Status Codes 1) [Laravel API 404 Error: Customize Exception Message](https://www.youtube.com/watch?v=SlBJrLnyoMk) 2) [HTTP Status Codes](https://httpstatuses.com/)

**Debugging Errors**

- [ ] Log Files in Laravel [Logging](https://laravel.com/docs/8.x/logging)
- [ ] Try-Catch and Laravel Exceptions 1) [Error Handling](https://laravel.com/docs/8.x/errors) 2) [Exceptions in Laravel: Why/How to Use and Create Your Own](https://www.youtube.com/watch?v=RTTXZVIL6tw)
- [ ] Local Debugging Tools: Debugbar, Telescope, Ray 1) [barryvdh/laravel-debugbar](https://github.com/barryvdh/laravel-debugbar) 2) [Laravel Telescope](https://laravel.com/docs/8.x/telescope) 3) [Spatie Ray (Premium Tool)](https://myray.app/) 4) [Debug Eloquent Queries from API: Laravel Telescope](https://www.youtube.com/watch?v=SR3RzIfeozI) 5) [Spatie Ray: Laravel Debugging with Pleasure](https://www.youtube.com/watch?v=n4pMxyAXeqY)
- [ ] Customizing Error Pages and Messages 1) [Custom HTTP Error Pages](https://laravel.com/docs/8.x/errors#custom-http-error-pages) 2) [Laravel Error Pages: Change Text or Customize Layouts](https://www.youtube.com/watch?v=iMAFUi6Z57k)
- [ ] (optional) Third Party Bug Trackers: Bugsnag, Flare, Sentry, Rollbar 1) [Bugsnag Laravel](https://docs.bugsnag.com/platforms/php/laravel/) 2) [Flare Homepage](https://flareapp.io/) 3) [Sentry Laravel](https://docs.sentry.io/platforms/php/guides/laravel/) 4) [Rollbar Laravel](https://docs.rollbar.com/docs/laravel) 5) [Bug Tracking in Laravel: Bugsnag vs Flare [Demo/Review]](https://www.youtube.com/watch?v=88UqUXhWwGA)

**Sending Email**

- [ ] Mailables and Mail Facade [Mail & Mailables](https://laravel.com/docs/8.x/mail)
- [ ] Configure Drivers/Services: Mailgun, Mailtrap, etc 1) [How to Send Email From Laravel, and Why We Need 3rd Party Providers For It](https://laraveldaily.com/how-to-send-email-from-laravel-and-why-we-need-3rd-party-providers-for-it/) 2) [Mail: Drivers Prerequisites](https://laravel.com/docs/8.x/mail#driver-prerequisites)
- [ ] Notifications System: Email, SMS, Slack, etc. [Notifications](https://laravel.com/docs/8.x/notifications)

**Automated Testing with PHPUnit**

- [ ] "Smoke" Tests to Check if Pages are Loading 1) [Testing: Getting Started](https://laravel.com/docs/8.x/testing) 2) [Laravel: PHPUnit Testing for Beginners](https://laraveldaily.teachable.com/p/laravel-phpunit-testing-for-beginners)
- [ ] Configure Testing Database and Test CRUD Operations [Database Testing](https://laravel.com/docs/8.x/database-testing)

**Deployment and Version Control**

- [ ] Git Version Control 1) [Git](https://git-scm.com/) 2) [Git in Laravel. Part 1 - Branches: Main, Develop and Feature](https://www.youtube.com/watch?v=AmScEC-_72I)
- [ ] Deployment on Live Servers 1) [Deployment](https://laravel.com/docs/8.x/deployment) 2) [How to Deploy Laravel Projects to Live Server: The Ultimate Guide](https://laraveldaily.com/how-to-deploy-laravel-projects-to-live-server-the-ultimate-guide/) 3) [What Server is Needed to Deploy Laravel Projects](https://laraveldaily.com/what-server-is-needed-to-deploy-laravel-projects/) 4) [How we Deploy Laravel: Branches, Staging Servers, Forge and Envoyer](https://www.youtube.com/watch?v=8DVuVftFZcQ)

### **Mid Level**

**Routing Extra Features**

- [ ] Route Caching [Route Caching](https://laravel.com/docs/8.x/routing#route-caching)
- [ ] Rate Limiting 1) [Rate Limiting](https://laravel.com/docs/8.x/routing#rate-limiting) 2) [Laravel: Create Public API with Cache and Rate Limits](https://www.youtube.com/watch?v=vrLcCxWlxOk)
- [ ] Invokable controllers [Single Action Controllers](https://laravel.com/docs/8.x/controllers#single-action-controllers)

**Database/Eloquent Extra Features**

- [ ] Model Observers 1) [Eloquent Observers](https://laravel.com/docs/8.x/eloquent#observers) 2) [Laravel Model: Check if Any Field Was Changed](https://www.youtube.com/watch?v=_xluet13xxE) 3) [Eloquent Observers or Events Listeners? Which is Better?](https://www.youtube.com/watch?v=DvoaU6cQQHM)
- [ ] Raw Database Queries [Query Builder: Raw Expressions](https://laravel.com/docs/8.x/queries#raw-expressions)
- [ ] All Eloquent Features 1) [All About Eloquent](https://laravel.com/docs/8.x/eloquent) 2) [Eloquent: Expert Level](https://laraveldaily.teachable.com/p/laravel-eloquent-expert-level) 3) [20 Laravel Eloquent Tips and Tricks](https://laravel-news.com/eloquent-tips-tricks)

**Various Extra Laravel Features**

- [ ] Custom Blade Directives [Extending Blade](https://laravel.com/docs/8.x/blade#extending-blade)
- [ ] Events and Listeners 1) [Events and Listeners](https://laravel.com/docs/8.x/events) 2) [Laravel: 3 Ways to Send a Welcome Email (Controller vs Observer vs Events)](https://www.youtube.com/watch?v=ZWzH6SOzjhI) 3) [Laravel: Why Observers and Event Listeners are "Risky"](https://www.youtube.com/watch?v=A3bmLo77e5M)
- [ ] Laravel HTTP Client and Guzzle 1) [HTTP Client](https://laravel.com/docs/8.x/http-client) 2) [Laravel and External APIs: Get Data with HTTP Client](https://www.youtube.com/watch?v=oEDDZsmMLc0)
- [ ] Login with X: Laravel Socialite [Laravel Socialite](https://laravel.com/docs/8.x/socialite)
- [ ] Creating Artisan Commands 1) [Writing Artisan Commands](https://laravel.com/docs/8.x/artisan#writing-commands) 2) [How to Create Artisan Commands in Laravel](https://www.youtube.com/watch?v=-r3WnYy7g48)
- [ ] Task Scheduling 1) [Task Scheduling](https://laravel.com/docs/8.x/scheduling) 2) [Laravel Task Scheduling: Run Artisan Command Hourly](https://www.youtube.com/watch?v=r-KrsQ0dN80)
- [ ] Caching 1) [Cache](https://laravel.com/docs/8.x/cache) 2) [Cache Eloquent Query Results to Load Pages Instantly](https://www.youtube.com/watch?v=JhKngeE0XJA)
- [ ] Real-time: Broadcasting, Echo and Pusher [Broadcasting](https://laravel.com/docs/8.x/broadcasting)

**Jobs and Queues** [Queues in Laravel](https://laraveldaily.teachable.com/p/queues-in-laravel)

- [ ] Queueable Classes and Jobs 1) [Creating Jobs](https://laravel.com/docs/8.x/queues#creating-jobs) 2) [Queueing Notifications](https://laravel.com/docs/8.x/notifications#queueing-notifications) 3) [Queued Event Listeners](https://laravel.com/docs/8.x/events#queued-event-listeners) 4) [Queueing Mail](https://laravel.com/docs/8.x/mail#queueing-mail) 5) [Laravel Queues 101: Example with Sending Emails](https://www.youtube.com/watch?v=rVx8xKisbr8)
- [ ] Job Dispatching, Batching and Chaining [Dispatching Jobs](https://laravel.com/docs/8.x/queues#dispatching-jobs)
- [ ] Processing Failed Jobs [Dealing with Failed Jobs](https://laravel.com/docs/8.x/queues#dealing-with-failed-jobs)
- [ ] Configuring Queues: Drivers, Redis, Supervisor 1) [Running the Queue Worker](https://laravel.com/docs/8.x/queues#running-the-queue-worker) 2) [Configuring Supervisor](https://laravel.com/docs/8.x/queues#supervisor-configuration)
- [ ] Laravel Horizon (optional, if you use Redis) [Laravel Horizon](https://laravel.com/docs/8.x/horizon)

**API Advanced**

- [ ] Upload Files via API [Laravel API: How to Upload File from Vue.js](https://blog.quickadminpanel.com/laravel-api-how-to-upload-file-from-vue-js/)
- [ ] Generate API Documentation 1) [Laravel API Documentation with OpenAPI/Swagger](https://blog.quickadminpanel.com/laravel-api-documentation-with-openapiswagger/) 2) [Scribe: New Package for Laravel API Documentation](https://www.youtube.com/watch?v=PjwGI8c2IfA)
- [ ] API Versioning 1) [Versioning your REST API with Laravel](https://codimth.com/blog/web/laravel/versioning-your-rest-api-laravel) 2) [Versioning your API: from V1 to V2 and Beyond [video from my course]](https://laraveldaily.teachable.com/courses/how-to-create-laravel-api/lectures/17568998)
- [ ] API with OAuth and Laravel Passport [Laravel Passport](https://laravel.com/docs/8.x/passport)
- [ ] Only-API Projects with Front-end like Vue.js [Vue.js + Laravel: CRUD with SPA](https://laraveldaily.teachable.com/p/vue-laravel-crud-spa)
- [ ] Only-API Projects with Mobile Apps [Using Sanctum to authenticate a mobile app](https://laravel-news.com/using-sanctum-to-authenticate-a-mobile-app)
**(optional) Starter Kits: Laravel Jetstream and Fortify**
- [ ] Laravel Jetstream (requires Livewire/Inertia knowledge) 1) [Laravel Jetstream](https://jetstream.laravel.com/) 2) [Laravel Jetstream+Livewire: Real Mini-Project](https://laraveldaily.teachable.com/p/laravel-jetstream-livewire-project) 3) [Laravel Jetstream: How it Works and Example How to Customize](https://www.youtube.com/watch?v=d8YgWApHMfA)
- [ ] Laravel Fortify 1) [Laravel Fortify](https://laravel.com/docs/8.x/fortify) 2) [Laravel Fortify: Four Auth Things to Customize](https://www.youtube.com/watch?v=Vr4LJU3kw1g)

**Payments**

- [ ] Laravel Cashier with Stripe/Paddle 1) [Laravel Cashier (Stripe)](https://laravel.com/docs/8.x/billing) 2) [Laravel Cashier (Paddle)](https://laravel.com/docs/8.x/cashier-paddle)
- [ ] Custom Payment Providers: PayPal, Mollie, etc 1) [Subscription billing with Laravel Cashier for Mollie](https://github.com/laravel/cashier-mollie) 2) [How To Integrate Paypal Payment Gateway In Laravel](https://websolutionstuff.com/post/how-to-integrate-paypal-payment-gateway-in-laravel)

**Automated Testing Advanced**

- [ ] TDD: Test-Driven Development 1) [Build A Laravel App With TDD](https://laracasts.com/series/build-a-laravel-app-with-tdd) 2) [TDD With Laravel](https://tddwithlaravel.com/)
- [ ] Mocking [Mocking](https://laravel.com/docs/8.x/mocking)
- [ ] (optional) Laravel Dusk [Laravel Dusk](https://laravel.com/docs/8.x/dusk)

**Full-Text Search**

- [ ] Laravel Scout [Laravel Scout](https://laravel.com/docs/8.x/scout)
- [ ] Drivers: ElasticSearch, Algolia or MeiliSearch 1) [ElasticSearch Driver for Laravel Scout](https://laravel-news.com/explorer) 2) [Algolia: Scout Extended](https://www.algolia.com/doc/framework-integration/laravel/getting-started/introduction-to-scout-extended/?client=php) 3) [Full-Text Search with MeiliSearch and Laravel Scout](https://tighten.co/blog/full-text-search-with-meilisearch-and-scout/)

**Laravel Packages**

- [ ] Contributing to Packages, making Pull Requests [How to Contribute to Laravel Docs (or any open-source repository)](https://www.youtube.com/watch?v=vEcT6JIFji0)
- [ ] Create Laravel Packages 1) [Package Development](https://laravel.com/docs/8.x/packages) 2) [Laravel Package Development](https://laravelpackage.com/)

### **Senior Level**

- [ ] PHP/Laravel Design Patterns 1) [Laravel Design Patterns - Bobby Bouwmann - Laracon EU 2018 Amsterdam](https://www.youtube.com/watch?v=qpo5KG0vIyE) 2) [Laracasts: Design Patterns in PHP](https://laracasts.com/series/design-patterns-in-php) 3) [Colin Decarlo - Design Patterns with Laravel [Laracon 2018]](https://www.youtube.com/watch?v=e4ugSgGaCQ0) 4) [Matt Stauffer - Patterns That Pay Off [Laracon 2018]](https://www.youtube.com/watch?v=enTb2E4vEos) 5) [Design Patterns in PHP](https://refactoring.guru/design-patterns/php)
- [ ] Creational Design Patterns [Design Patterns PHP: Creational](https://designpatternsphp.readthedocs.io/en/latest/Creational/README.html)
- [ ] Structural Design Patterns [Design Patterns PHP: Structural](https://designpatternsphp.readthedocs.io/en/latest/Structural/README.html)
- [ ] Behavioral Design Patterns [Design Patterns PHP: Behavioral](https://designpatternsphp.readthedocs.io/en/latest/Behavioral/README.html)

**Well-written Code**

- [ ] SOLID Code 1) [Becoming a better developer by using the SOLID design principles by Katerina Trajchevska](https://www.youtube.com/watch?v=rtmFCcjEgEw) 2) [Writing Maintainable Code: SOLID Principles Explained in PHP (Laravel)](https://geekflare.com/php-solid-principles/) 3) [Laracasts: SOLID Principles in PHP](https://laracasts.com/series/solid-principles-in-php) 4) [PHP Solid Principles [Playlist]](https://www.youtube.com/watch?v=ARxZV8OZ8Cg&list=PLNuh5_K9dfQ3jMU-2C2jYRGe2iXJkpCZj)
- [ ] Scalable Code 1) [Scaling Laravel](https://courses.serversforhackers.com/scaling-laravel) 2) [Enterprise Laravel by Matt Stauffer](https://enterpriselaravel.com/) 3) [What the hell is scalable code anyway?](https://blog.sarasarya.com/what-the-hell-is-scalable-code-anyway-f6626ad78227)
- [ ] Maintainable Code 1) [How would you know if you've written readable and easily maintainable code? [forum thread]](https://softwareengineering.stackexchange.com/questions/141005/how-would-you-know-if-youve-written-readable-and-easily-maintainable-code) 2) [Crafting maintainable Laravel applications](https://jasonmccreary.me/articles/crafting-maintainable-laravel-applications/) 3) [7 Golden Rules of Clean, Simple and Maintainable Code](https://shhetri.github.io/clean-code/#/)
- [ ] Best Practices and Standards 1) [Repository: alexeymezenin / laravel-best-practices](https://github.com/alexeymezenin/laravel-best-practices) 2) [PHP: The Right Way](https://phptherightway.com/) 3) [Reddit: What are your Laravel best practices?](https://www.reddit.com/r/laravel/comments/f34t86/what_are_your_laravel_best_practices/)

**Large Datasets**

- [ ] Large Database Structures [How to Structure Databases in Laravel](https://laraveldaily.teachable.com/p/how-to-structure-database-in-laravel)
- [ ] NoSQL Solutions 1) [MongoDB and Laravel Integration](https://www.mongodb.com/compatibility/mongodb-laravel-intergration) 2) [MongoDB + Laravel = Love — When to use NoSQL](https://faun.pub/when-to-use-nosql-getting-started-with-mongodb-in-laravel-f5376ceaf545)
- [ ] Eloquent/SQL Query Optimization 1) [18 Tips to optimize laravel database queries](https://dudi.dev/optimize-laravel-database-queries/) 2) [Optimizing Laravel Part 2: Improving Query Performance with Database Indexing](https://deliciousbrains.com/optimizing-laravel-database-indexing-performance/) 3) [Eloquent Performance Patterns](https://eloquent-course.reinink.ca/)
- [ ] Scaling to Multiple Databases 1) [Scaling Laravel App with Multiple Databases](https://devdojo.com/bobbyiliev/scaling-laravel-app-with-multiple-databases) 2) [Multiple DB Connections in Laravel](https://fideloper.com/laravel-multiple-database-connections)

**Working with High-Traffic Projects**

- [ ] Stability and Zero-Downtime Deployments 1) [Laravel Deployer](https://github.com/lorisleiva/laravel-deployer) 2) [Envoyer - Zero Downtime PHP Deployment](https://envoyer.io/)
- [ ] Performance Optimization and Caching 1) [Performant Laravel](https://serversforhackers.com/laravel-perf) 2) [The Ultimate Performance Checklist For Laravel Apps](https://laravel-news.com/performance-checklist) 3) [How to Optimize PHP Laravel Web Application for High Performance?](https://geekflare.com/laravel-optimization/)

**Ensuring Code Quality**

- [ ] Writing Testable Code 1) [How to write testable code](https://dev.to/ddarrko/how-to-write-more-testable-code-oi7) 2) [Refactoring towards testability](https://madewithlove.com/blog/software-engineering/refactoring-untestable-code-towards-testability/)
- [ ] Continuous Integration and Continuous Delivery (CI/CD) 1) [How to create a CI/CD for a Laravel application using GitHub Actions](https://blog.logrocket.com/how-to-create-a-ci-cd-for-a-laravel-application-using-github-actions/) 2) [Configure Laravel 8 for CI/CD with Jenkins and GitHub — Part 1](https://faun.pub/configure-laravel-8-for-ci-cd-with-jenkins-and-github-part-1-58b9be304292) 3) [Build, Test, and Deploy Your Laravel Application With GitHub Actions](https://www.twilio.com/blog/build-test-deploy-laravel-application-github-actions)
